// Code generated by hand for this project — minimal protobuf-like types.
package pb

import "time"

type Product struct {
    Id uint32
    Code string
    Name string
    Description string
    Stock int32
    CreatedAt time.Time
    UpdatedAt time.Time
}

type Reservation struct {
    Id uint32
    ProductId uint32
    OrderId uint32
    Quantity int32
    Status string
    CreatedAt time.Time
    UpdatedAt time.Time
}

type ListProductsRequest struct {
    Page int32
    PerPage int32
    Search string
}

type ListProductsResponse struct {
    Products []*Product
    Total int32
}

type GetProductRequest struct { Id uint32 }
type GetProductResponse struct { Product *Product }

type CreateReservationRequest struct { Reservation *Reservation }
type CreateReservationResponse struct { Reservation *Reservation }

type ListReservationsRequest struct { Page int32; PerPage int32 }
type ListReservationsResponse struct { Reservations []*Reservation; Total int32 }
type GetReservationRequest struct { Id uint32 }
type GetReservationResponse struct { Reservation *Reservation }
