// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"inventory-service/internal/adapter/repository/postgres"
	"inventory-service/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReservationRepository creates a new instance of MockReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationRepository {
	mock := &MockReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReservationRepository is an autogenerated mock type for the ReservationRepository type
type MockReservationRepository struct {
	mock.Mock
}

type MockReservationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationRepository) EXPECT() *MockReservationRepository_Expecter {
	return &MockReservationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) Create(ctx context.Context, reservation *entity.Reservation) (*entity.Reservation, error) {
	ret := _mock.Called(ctx, reservation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Reservation) (*entity.Reservation, error)); ok {
		return returnFunc(ctx, reservation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Reservation) *entity.Reservation); ok {
		r0 = returnFunc(ctx, reservation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Reservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Reservation) error); ok {
		r1 = returnFunc(ctx, reservation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReservationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - reservation *entity.Reservation
func (_e *MockReservationRepository_Expecter) Create(ctx interface{}, reservation interface{}) *MockReservationRepository_Create_Call {
	return &MockReservationRepository_Create_Call{Call: _e.mock.On("Create", ctx, reservation)}
}

func (_c *MockReservationRepository_Create_Call) Run(run func(ctx context.Context, reservation *entity.Reservation)) *MockReservationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Reservation
		if args[1] != nil {
			arg1 = args[1].(*entity.Reservation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationRepository_Create_Call) Return(reservation1 *entity.Reservation, err error) *MockReservationRepository_Create_Call {
	_c.Call.Return(reservation1, err)
	return _c
}

func (_c *MockReservationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, reservation *entity.Reservation) (*entity.Reservation, error)) *MockReservationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) Find(ctx context.Context, filter *postgresrepository.FilterReservationPayload) ([]*entity.Reservation, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []*entity.Reservation
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *postgresrepository.FilterReservationPayload) ([]*entity.Reservation, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *postgresrepository.FilterReservationPayload) []*entity.Reservation); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Reservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *postgresrepository.FilterReservationPayload) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *postgresrepository.FilterReservationPayload) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReservationRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockReservationRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *postgresrepository.FilterReservationPayload
func (_e *MockReservationRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockReservationRepository_Find_Call {
	return &MockReservationRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockReservationRepository_Find_Call) Run(run func(ctx context.Context, filter *postgresrepository.FilterReservationPayload)) *MockReservationRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *postgresrepository.FilterReservationPayload
		if args[1] != nil {
			arg1 = args[1].(*postgresrepository.FilterReservationPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationRepository_Find_Call) Return(reservations []*entity.Reservation, n int, err error) *MockReservationRepository_Find_Call {
	_c.Call.Return(reservations, n, err)
	return _c
}

func (_c *MockReservationRepository_Find_Call) RunAndReturn(run func(ctx context.Context, filter *postgresrepository.FilterReservationPayload) ([]*entity.Reservation, int, error)) *MockReservationRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) FindByID(ctx context.Context, id uint32) (*entity.Reservation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (*entity.Reservation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) *entity.Reservation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Reservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockReservationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockReservationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockReservationRepository_FindByID_Call {
	return &MockReservationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockReservationRepository_FindByID_Call) Run(run func(ctx context.Context, id uint32)) *MockReservationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationRepository_FindByID_Call) Return(reservation *entity.Reservation, err error) *MockReservationRepository_FindByID_Call {
	_c.Call.Return(reservation, err)
	return _c
}

func (_c *MockReservationRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint32) (*entity.Reservation, error)) *MockReservationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) UpdateStatus(ctx context.Context, ids []uint32, status string) error {
	ret := _mock.Called(ctx, ids, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint32, string) error); ok {
		r0 = returnFunc(ctx, ids, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReservationRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockReservationRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint32
//   - status string
func (_e *MockReservationRepository_Expecter) UpdateStatus(ctx interface{}, ids interface{}, status interface{}) *MockReservationRepository_UpdateStatus_Call {
	return &MockReservationRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, ids, status)}
}

func (_c *MockReservationRepository_UpdateStatus_Call) Run(run func(ctx context.Context, ids []uint32, status string)) *MockReservationRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint32
		if args[1] != nil {
			arg1 = args[1].([]uint32)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReservationRepository_UpdateStatus_Call) Return(err error) *MockReservationRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReservationRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, ids []uint32, status string) error) *MockReservationRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
